#pragma once

#include <stddef.h>

enum VmAssemblyError {
	VM_ASSEMBLY_SUCCESS = 0,
	VM_ASSEMBLY_ERROR_EMPTY_LABEL,
	VM_ASSEMBLY_ERROR_EMPTY_PROGRAM,
	VM_ASSEMBLY_ERROR_LABEL_IS_TOO_LONG,
	VM_ASSEMBLY_ERROR_TOO_MANY_LABELS,
	VM_ASSEMBLY_ERROR_INVALID_COMMAND,
	VM_ASSEMBLY_ERROR_INVALID_EXPRESSION,
	VM_ASSEMBLY_ERROR_INVALID_ARG,
	VM_ASSEMBLY_ERROR_WHILE_WRITING
	VM_ASSEMBLY_ERROR_WHILE_READING
};

struct VmAssemblyStatus {
	size_t line;
	AssemblyError error;
};