// #define COMMAND(NAME, NUMBER, ENCODING_CODE, DECODING_CODE, EXECUTION_CODE)
// 

COMMAND(halt, 0, {
	WRITE_BIT_TO_CODE(0);
	WRITE_BIT_TO_CODE(0);
	WRITE_BIT_TO_CODE(0);
	WRITE_BIT_TO_CODE(0);
	WRITE_BIT_TO_CODE(0);
	WRITE_BIT_TO_CODE(0);
	WRITE_BIT_TO_CODE(0);
	WRITE_BIT_TO_CODE(0);
})
COMMAND(push, 1
)