// #define COMMAND(NAME, NUMBER, ALLOWED_ARG_TYPES...)
// Arg type is 3 bits: uses memory, uses register, uses immediate const.

#include "arg_type.h"

#include "support/macro_utils.h"

COMMAND(halt, 0, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)

COMMAND(
	push,
	1,
	ARRAY_DEF(
		VM_COMMAND_ARG_USES_MEMORY | VM_COMMAND_ARG_USES_REGISTER | VM_COMMAND_ARG_USES_IMMEDIATE_CONST,
		VM_COMMAND_ARG_USES_MEMORY |                             VM_COMMAND_ARG_USES_IMMEDIATE_CONST,
		VM_COMMAND_ARG_USES_MEMORY | VM_COMMAND_ARG_USES_REGISTER                                   ,
		                          VM_COMMAND_ARG_USES_REGISTER | VM_COMMAND_ARG_USES_IMMEDIATE_CONST,
		                                                      VM_COMMAND_ARG_USES_IMMEDIATE_CONST,
		                          VM_COMMAND_ARG_USES_REGISTER
	),
)

COMMAND(
	pop,
	2,
	ARRAY_DEF(
		VM_COMMAND_ARG_USES_MEMORY | VM_COMMAND_ARG_USES_REGISTER | VM_COMMAND_ARG_USES_IMMEDIATE_CONST,
		VM_COMMAND_ARG_USES_MEMORY |                             VM_COMMAND_ARG_USES_IMMEDIATE_CONST,
		VM_COMMAND_ARG_USES_MEMORY | VM_COMMAND_ARG_USES_REGISTER                                   ,
		                          VM_COMMAND_ARG_USES_REGISTER
	),
)

COMMAND(add,  3, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)
COMMAND(sub,  4, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)
COMMAND(mul,  5, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)
COMMAND(div,  6, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)

COMMAND(shr,  7, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)
COMMAND(shl,  8, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)
COMMAND(and,  9, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)
COMMAND( or, 10, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)
COMMAND(xor, 11, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)

COMMAND(out, 12, ARRAY_DEF(VM_COMMAND_ARG_NOT_PRESENT),)
