#pragma once

#include <stddef.h>

enum VMStatus {
	VM_SUCCESS = 0,
	// VM_ASSEMBLY_ERROR_EMPTY_LABEL,
	VM_ASSEMBLY_ERROR_EMPTY_PROGRAM,
	VM_ASSEMBLY_ERROR_INVALID_LABEL_DECL, // Incorrect? Something less strict.
	VM_ASSEMBLY_ERROR_INVALID_COMMAND,
	VM_ASSEMBLY_ERROR_INVALID_ARGUMENT,
	VM_ASSEMBLY_ERROR_INVALID_DIRECTIVE,
	VM_ASSEMBLY_ERROR_INVALID_EXPRESSION,
	VM_ASSEMBLY_ERROR_LABEL_IS_TOO_LONG,
	VM_ASSEMBLY_ERROR_TOO_MANY_LABELS,
	VM_ASSEMBLY_ERROR_MULTIPLE_DEFINITION_OF_LABEL,
	VM_ERROR_INSUFFICIENT_BUFFER,
	VM_ERROR_WHILE_WRITING,
	VM_ERROR_WHILE_READING,
	VM_ERROR_DEBUGGER_NOT_PRESENT,
	VM_STATUS_HALT_REQUESTED
};

const char* vm_status_to_string(VMStatus status);
