#pragma once

#include "support/macro_utils.h"

#define VM_ASSEMBLY_MAX_COMMAND_LENGTH_MACRO 10
#define VM_COMMAND_NAME_SCANF_FORMAT "%" EXPAND(VM_ASSEMBLY_MAX_COMMAND_LENGTH_MACRO) "s"

static const size_t VM_ASSEMBLY_MAX_COMMAND_LENGTH = VM_ASSEMBLY_MAX_COMMAND_LENGTH_MACRO;
